version: '3.8'

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jwk-token
    ports:
      - "1111:3007"
    depends_on:
      - database
    command: ["wait-for-it.sh", "database", "--", "./main"]
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=jwk-practice

  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jwk-practice
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3307:3306'
    restart: unless-stopped

volumes:
  my-db:
